// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, email string) (*User, error)
	InsertUser(ctx context.Context, arg *InsertUserParams) (string, error)
}

var _ Querier = (*Queries)(nil)
